version: '3'
services:
  web:
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - UPDATE=0
      - ENVIRONMENT
      - SECRET_KEY_BASE
      - ASTUTO_PG_USER
      - ASTUTO_PG_PASS
      - ASTUTO_PG_HOST
      - ASTUTO_PG_DB
      - EMAIL_CONFIRMATION
      - APP_NAME
      - SHOW_LOGO
      - POSTS_PER_PAGE
    volumes:
      - .:/astuto
    ports:
      - "3000:3000"
